platform :ios,  '12.0'
use_frameworks!

target 'FLEX_Example' do
  pod 'FLEX', :path => '../'

  target 'FLEX_Tests' do
    inherit! :search_paths

    pod 'Quick', '1.3.0'
    pod 'Nimble', '7.3.1'
  end
end

post_install do |installer|
  testPods = ['Quick', 'Nimble']

  installer.pods_project.targets.each do |target| 
    target.build_configurations.each do |config| 
      config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = "NO"
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
    end 
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
